repos:
  -
    repo: local
    hooks:
      -
        id: isort
        name: 'Run isort import sorter/organizer'
        entry: 'env/bin/isort --check-only --diff --filter-files'
        language: system
        types:
          - python
      -
        id: black
        name: 'Run black code formatter'
        entry: 'env/bin/black --check --diff'
        language: system
        types:
          - python
      -
        id: flake8
        name: 'Run flake8 linter'
        entry: 'env/bin/flake8'
        language: system
        types:
          - python
      -
        id: mypy
        name: 'Run mypy static type checker'
        entry: 'env/bin/mypy'
        language: system
        types:
          - python
